### PR TITLE
Add git project subdirectories as symlink projects

### PR DESCRIPTION
**Pull request by awnawab**
To allow greater flexibility in compiling ifs-source components independently, they can be added as symlinked projects to the bundle. This small PR adds this functionality. Once approved and merged, could I please request a tag with this change included.

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](https://bol-claassistant.ecmwf.int:443/ecmwf/ecbundle?pullRequest=6) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf/ecbundle?pullRequest=6) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf/ecbundle?pullRequest=6) it.</sub>

**Comment by awnawab** [comment]
Hi @wdeconinck. I can't seem to be able to request a review via the usual channel. Could you please review this PR?

**Comment by wdeconinck** [comment]
Hi @awnawab could you explain by example, and add a test?

**Review by wdeconinck — APPROVED** [review]
Looks great! Thanks @awnawab

**Comment by wdeconinck** [comment]
@awnawab  this is now in version 2.1.0

**Pull request merged**
